sudo: required
dist: trusty
language: cpp

env:
    - BUILDTYPE=Release
    - BUILDTYPE=Debug

before_install:
    - sudo apt-get update -qq

install:
    - ls

script:
    - cd ucore
    - pwd
    - python misc/evaluate_build.py /tmp/ucore_build_env

compiler:
    - gcc
