sudo: required
dist: trusty
language: cpp
services: docker

env:
    - BUILDTYPE=Release
    - BUILDTYPE=Debug

before_install:
    - sudo docker pull tinytangent/ucore_build_environment
    - sudo apt-get update -qq

install:
    - ls

script:
    - docker cp -r ucore tinytangent/ucore_build_environment:/
    - docker run tinytangent/ucore_build_environment pwd
    - docker run tinytangent/ucore_build_environment ls
    - docker run tinytangent/ucore_build_environment ls /
    - docker run tinytangent/ucore_build_environment ls /opt
    - pwd
    - python misc/evaluate_build.py /tmp/ucore_build_env

compiler:
    - gcc
