sudo: required
dist: trusty
language: cpp
services: docker

env:
    - BUILDTYPE=Default

before_install:
    - sudo docker pull tinytangent/ucore_build_environment
    - sudo docker create --name=ucore_build_environment -it tinytangent/ucore_build_environment
    - sudo apt-get update -qq

install:
    - ls

script:
    - docker cp ucore ucore_build_environment:/
    - docker start ucore_build_environment
    - docker exec ucore_build_environment pwd
    - docker exec ucore_build_environment ls
    - docker exec ucore_build_environment ls /
    - docker exec ucore_build_environment ls /opt
    - pwd
    - python misc/evaluate_build.py /tmp/ucore_build_env

compiler:
    - gcc
